export interface AITool {
  id: string
  name: string
  tagline: string
  description: string
  category: 'chatbot' | 'image' | 'search' | 'code' | 'multimodal' | 'voice'
  url: string
  logo: string
  cover: string
  color: string
  gradient: string
  badge?: string
  features: string[]
  company: string
  free: boolean
  popular?: boolean
}

export interface Prompt {
  id: number
  title: string
  platform: string
  content: string
  date: string
}

export const AI_TOOLS: AITool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'The world\'s most popular AI assistant',
    description: 'GPT-4o powered conversational AI by OpenAI. Write, code, analyze, create — with advanced reasoning and multimodal capabilities.',
    category: 'chatbot',
    url: 'https://chat.openai.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/512px-ChatGPT_logo.svg.png',
    cover: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=85&auto=format&fit=crop',
    color: '#10b981',
    gradient: 'from-emerald-500/20 to-teal-500/10',
    badge: 'Most Popular',
    features: ['GPT-4o', 'Code Interpreter', 'DALL-E 3', 'Web Browse'],
    company: 'OpenAI',
    free: true,
    popular: true,
  },
  {
    id: 'claude',
    name: 'Claude',
    tagline: 'The thoughtful AI assistant by Anthropic',
    description: 'Constitutional AI built for safety and nuance. Claude 3.5 Sonnet excels at long-form writing, analysis, and complex reasoning tasks.',
    category: 'chatbot',
    url: 'https://claude.ai',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Claude_AI_logo.svg/512px-Claude_AI_logo.svg.png',
    cover: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=85&auto=format&fit=crop',
    color: '#f97316',
    gradient: 'from-orange-500/20 to-amber-500/10',
    badge: 'Best for Writing',
    features: ['200K Context', 'Artifacts', 'Vision', 'Code'],
    company: 'Anthropic',
    free: true,
    popular: true,
  },
  {
    id: 'gemini',
    name: 'Gemini',
    tagline: 'Google\'s most capable AI model',
    description: 'Gemini 1.5 Pro from Google DeepMind. Natively multimodal with 1M token context window, integrated with Google Workspace.',
    category: 'multimodal',
    url: 'https://gemini.google.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Google_Gemini_logo.svg/512px-Google_Gemini_logo.svg.png',
    cover: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=800&q=85&auto=format&fit=crop',
    color: '#3b82f6',
    gradient: 'from-blue-500/20 to-violet-500/10',
    features: ['1M Context', 'Google Search', 'Multimodal', 'Workspace'],
    company: 'Google',
    free: true,
    popular: true,
  },
  {
    id: 'grok',
    name: 'Grok',
    tagline: 'Real-time AI with a sense of humor',
    description: 'Built by xAI, Grok has real-time access to X (Twitter) data and the internet. Known for wit, directness, and up-to-the-minute knowledge.',
    category: 'chatbot',
    url: 'https://grok.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Xai-logo.svg/512px-Xai-logo.svg.png',
    cover: 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=800&q=85&auto=format&fit=crop',
    color: '#dc2626',
    gradient: 'from-red-500/20 to-rose-500/10',
    badge: 'Real-time',
    features: ['X Data Access', 'Real-time Web', 'Image Gen', 'Voice'],
    company: 'xAI',
    free: true,
    popular: true,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    tagline: 'Open-source reasoning powerhouse',
    description: 'DeepSeek R1 — the open-source model that shook the AI world. Exceptional at mathematics, code, and multi-step logical reasoning.',
    category: 'chatbot',
    url: 'https://chat.deepseek.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/DeepSeek_logo.svg/512px-DeepSeek_logo.svg.png',
    cover: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=85&auto=format&fit=crop',
    color: '#6366f1',
    gradient: 'from-indigo-500/20 to-violet-500/10',
    badge: 'Open Source',
    features: ['R1 Reasoning', 'Open Source', 'Code Expert', 'Math'],
    company: 'DeepSeek AI',
    free: true,
    popular: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    tagline: 'AI-powered answer engine',
    description: 'Perplexity AI combines real-time web search with AI synthesis. Get cited, accurate answers to any question with live sources.',
    category: 'search',
    url: 'https://www.perplexity.ai',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Perplexity_AI_logo.svg/512px-Perplexity_AI_logo.svg.png',
    cover: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&q=85&auto=format&fit=crop',
    color: '#14b8a6',
    gradient: 'from-teal-500/20 to-cyan-500/10',
    badge: 'Best Search',
    features: ['Live Search', 'Citations', 'Academic', 'Copilot'],
    company: 'Perplexity AI',
    free: true,
    popular: true,
  },
  {
    id: 'dola',
    name: 'Dola',
    tagline: 'AI calendar assistant via messaging',
    description: 'Dola is your AI scheduling assistant. Add events, set reminders, and manage your calendar directly through WhatsApp, Telegram, or iMessage.',
    category: 'chatbot',
    url: 'https://dola.me',
    logo: 'https://dola.me/icon.png',
    cover: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=85&auto=format&fit=crop',
    color: '#06b6d4',
    gradient: 'from-cyan-500/20 to-sky-500/10',
    features: ['Calendar AI', 'WhatsApp', 'Telegram', 'Reminders'],
    company: 'Dola',
    free: true,
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    tagline: 'Your everyday AI companion by Microsoft',
    description: 'Microsoft Copilot is powered by GPT-4 Turbo and integrated into Windows, Edge, and Microsoft 365. AI everywhere you need it.',
    category: 'multimodal',
    url: 'https://copilot.microsoft.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Microsoft_365_Copilot_Icon.svg/512px-Microsoft_365_Copilot_Icon.svg.png',
    cover: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=85&auto=format&fit=crop',
    color: '#0ea5e9',
    gradient: 'from-sky-500/20 to-blue-500/10',
    features: ['Microsoft 365', 'Designer', 'Windows', 'Edge'],
    company: 'Microsoft',
    free: true,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    tagline: 'The gold standard of AI image generation',
    description: 'Midjourney v6 produces the most aesthetically stunning AI art in existence. Used by professionals worldwide for concept art, design, and photography.',
    category: 'image',
    url: 'https://www.midjourney.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Midjourney_Emblem.png/512px-Midjourney_Emblem.png',
    cover: 'https://images.unsplash.com/photo-1686191128892-3b37add4c844?w=800&q=85&auto=format&fit=crop',
    color: '#8b5cf6',
    gradient: 'from-violet-500/20 to-purple-500/10',
    badge: 'Best Images',
    features: ['v6 Model', 'Style Raw', 'Upscale 4x', 'Vary Region'],
    company: 'Midjourney',
    free: false,
    popular: true,
  },
  {
    id: 'llama',
    name: 'Meta Llama',
    tagline: 'Open-source AI from Meta',
    description: 'Llama 3.1 by Meta — fully open-source large language models. Run locally or in the cloud. The foundation for countless AI applications.',
    category: 'chatbot',
    url: 'https://llama.meta.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Meta-Logo.png/512px-Meta-Logo.png',
    cover: 'https://images.unsplash.com/photo-1517134191118-9d595e4c8c2b?w=800&q=85&auto=format&fit=crop',
    color: '#84cc16',
    gradient: 'from-lime-500/20 to-green-500/10',
    badge: 'Open Source',
    features: ['405B Model', 'Local Run', 'Fine-tunable', 'Commercial'],
    company: 'Meta',
    free: true,
  },
  {
    id: 'qwen',
    name: 'Qwen AI',
    tagline: 'Alibaba\'s frontier AI model',
    description: 'Qwen2.5 by Alibaba Cloud — top-tier performance especially in Chinese language tasks, coding, and mathematics. Competitive with frontier models.',
    category: 'chatbot',
    url: 'https://qwenlm.github.io',
    logo: 'https://qianwen-res.oss-accelerate-overseas.aliyuncs.com/assets/blog/qwenvl/logo.jpg',
    cover: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=85&auto=format&fit=crop',
    color: '#f59e0b',
    gradient: 'from-amber-500/20 to-yellow-500/10',
    features: ['Multilingual', 'Code', 'Math', 'Vision'],
    company: 'Alibaba',
    free: true,
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    tagline: 'Open-source image generation',
    description: 'Stable Diffusion by Stability AI — the original open-source text-to-image model. Fully customizable, runs locally, with thousands of community models.',
    category: 'image',
    url: 'https://stability.ai',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Stability_AI_logo.svg/512px-Stability_AI_logo.svg.png',
    cover: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&q=85&auto=format&fit=crop',
    color: '#ec4899',
    gradient: 'from-pink-500/20 to-rose-500/10',
    badge: 'Open Source',
    features: ['SDXL', 'Local Run', 'ControlNet', 'Inpainting'],
    company: 'Stability AI',
    free: true,
  },
]

export const CATEGORIES = [
  { id: 'all', label: 'Semua' },
  { id: 'chatbot', label: 'Chatbot' },
  { id: 'image', label: 'Image AI' },
  { id: 'search', label: 'AI Search' },
  { id: 'code', label: 'Code AI' },
  { id: 'multimodal', label: 'Multimodal' },
]

export const PLATFORMS = AI_TOOLS.map(t => t.name)

export const DEFAULT_PROMPTS: Prompt[] = [
  {
    id: 1,
    title: 'Creative Story Writer',
    platform: 'ChatGPT',
    content: 'You are a creative fiction writer. Write a compelling short story based on the following premise. Use vivid descriptions, engaging dialogue, and a surprising twist ending. The story should be between 500-1000 words. Make the characters feel real and relatable. Include sensory details that immerse the reader in the world you create. The tone should match the genre specified. Begin with a hook that grabs attention immediately.',
    date: '2026-03-11',
  },
  {
    id: 2,
    title: 'Midjourney Cinematic Portrait',
    platform: 'Midjourney',
    content: 'A cinematic portrait of a young woman standing in a neon-lit Tokyo alley at night, rain-soaked streets reflecting colorful signs, shallow depth of field, shot on Sony A7III, 85mm lens, f/1.4, moody atmosphere, volumetric lighting, cyberpunk aesthetic, ultra realistic, 8k resolution, dramatic shadows, film grain',
    date: '2026-03-10',
  },
  {
    id: 3,
    title: 'Code Review Assistant',
    platform: 'Claude',
    content: 'You are an expert senior software engineer conducting a thorough code review. Analyze the following code for: 1) Bugs and potential errors, 2) Performance issues, 3) Security vulnerabilities, 4) Code style and readability, 5) Best practices violations, 6) Potential edge cases. Provide specific line-by-line feedback with suggested improvements. Rate the overall code quality on a scale of 1-10.',
    date: '2026-03-09',
  },
  {
    id: 4,
    title: 'SEO Blog Article Generator',
    platform: 'Gemini',
    content: 'Write a comprehensive, SEO-optimized blog article about the given topic. Include: an engaging H1 title with the main keyword, a meta description (155 chars max), proper H2 and H3 subheadings, bullet points and numbered lists where appropriate, a FAQ section with 5 common questions, and a compelling call-to-action. The article should be 1500-2000 words, written in a conversational yet authoritative tone.',
    date: '2026-03-08',
  },
  {
    id: 5,
    title: 'Stable Diffusion Landscape',
    platform: 'Stable Diffusion',
    content: 'masterpiece, best quality, ultra detailed, 8k wallpaper, breathtaking mountain landscape at golden hour, dramatic clouds, crystal clear lake reflection, pine forest in foreground, snow-capped peaks, volumetric god rays, cinematic composition, professional photography, sharp focus, high dynamic range, vibrant colors, National Geographic style, panoramic view, serene atmosphere',
    date: '2026-03-07',
  },
  {
    id: 6,
    title: 'Data Analysis Expert',
    platform: 'ChatGPT',
    content: 'You are a data analysis expert. I will provide you with a dataset or data description. Please: 1) Identify key patterns and trends, 2) Suggest appropriate statistical methods, 3) Create visualization recommendations, 4) Provide actionable insights, 5) Highlight any anomalies or outliers, 6) Recommend next steps for deeper analysis. Present your findings in a clear, structured format with headers and bullet points.',
    date: '2026-03-05',
  },
]
